import { PullStream } from '../core/pull-stream.js';

/**
 * Pipes a PullStream through a sequence of transform operators.
 *
 * @remarks
 * Takes an input PullStream and applies each transform function in order, returning the final transformed PullStream.
 *
 * @example
 * ```ts
 * import { pipe } from './pipe.js';
 * import { map } from '../operator/map.js';
 * import { filter } from '../operator/filter.js';
 * import { from } from '../generator/from.js';
 *
 * const result = pipe(
 *   from(1, 2, 3, 4),
 *   (e) => map(e, (x) => x * 2),
 *   (e) => filter(e, (x) => x > 4)
 * );
 * // result yields 6, 8
 * ```
 *
 * @param stream - The input PullStream
 * @param args - Transform functions to apply in sequence
 * @returns The transformed PullStream after all operators are applied
 */

export function pipe<T1, T2>(
  stream: PullStream<T1>,
  fn: (stream: PullStream<T1>) => PullStream<T2>,
): PullStream<T2>;
export function pipe<T1, T2, T3>(
  stream: PullStream<T1>,
  fn1: (stream: PullStream<T1>) => PullStream<T2>,
  fn2: (stream: PullStream<T2>) => PullStream<T3>,
): PullStream<T3>;
export function pipe<T1, T2, T3, T4>(
  stream: PullStream<T1>,
  fn1: (stream: PullStream<T1>) => PullStream<T2>,
  fn2: (stream: PullStream<T2>) => PullStream<T3>,
  fn3: (stream: PullStream<T3>) => PullStream<T4>,
): PullStream<T4>;
export function pipe<T1, T2, T3, T4, T5>(
  stream: PullStream<T1>,
  fn1: (stream: PullStream<T1>) => PullStream<T2>,
  fn2: (stream: PullStream<T2>) => PullStream<T3>,
  fn3: (stream: PullStream<T3>) => PullStream<T4>,
  fn4: (stream: PullStream<T4>) => PullStream<T5>,
): PullStream<T5>;
export function pipe<T1, T2, T3, T4, T5, T6>(
  stream: PullStream<T1>,
  fn1: (stream: PullStream<T1>) => PullStream<T2>,
  fn2: (stream: PullStream<T2>) => PullStream<T3>,
  fn3: (stream: PullStream<T3>) => PullStream<T4>,
  fn4: (stream: PullStream<T4>) => PullStream<T5>,
  fn5: (stream: PullStream<T5>) => PullStream<T6>,
): PullStream<T6>;
export function pipe<T1, T2, T3, T4, T5, T6, T7>(
  stream: PullStream<T1>,
  fn1: (stream: PullStream<T1>) => PullStream<T2>,
  fn2: (stream: PullStream<T2>) => PullStream<T3>,
  fn3: (stream: PullStream<T3>) => PullStream<T4>,
  fn4: (stream: PullStream<T4>) => PullStream<T5>,
  fn5: (stream: PullStream<T5>) => PullStream<T6>,
  fn6: (stream: PullStream<T6>) => PullStream<T7>,
): PullStream<T7>;
export function pipe<T1, T2, T3, T4, T5, T6, T7, T8>(
  stream: PullStream<T1>,
  fn1: (stream: PullStream<T1>) => PullStream<T2>,
  fn2: (stream: PullStream<T2>) => PullStream<T3>,
  fn3: (stream: PullStream<T3>) => PullStream<T4>,
  fn4: (stream: PullStream<T4>) => PullStream<T5>,
  fn5: (stream: PullStream<T5>) => PullStream<T6>,
  fn6: (stream: PullStream<T6>) => PullStream<T7>,
  fn7: (stream: PullStream<T7>) => PullStream<T8>,
): PullStream<T8>;
export function pipe<T1, T2, T3, T4, T5, T6, T7, T8, T9>(
  stream: PullStream<T1>,
  fn1: (stream: PullStream<T1>) => PullStream<T2>,
  fn2: (stream: PullStream<T2>) => PullStream<T3>,
  fn3: (stream: PullStream<T3>) => PullStream<T4>,
  fn4: (stream: PullStream<T4>) => PullStream<T5>,
  fn5: (stream: PullStream<T5>) => PullStream<T6>,
  fn6: (stream: PullStream<T6>) => PullStream<T7>,
  fn7: (stream: PullStream<T7>) => PullStream<T8>,
  fn8: (stream: PullStream<T8>) => PullStream<T9>,
): PullStream<T9>;
export function pipe<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(
  stream: PullStream<T1>,
  fn1: (stream: PullStream<T1>) => PullStream<T2>,
  fn2: (stream: PullStream<T2>) => PullStream<T3>,
  fn3: (stream: PullStream<T3>) => PullStream<T4>,
  fn4: (stream: PullStream<T4>) => PullStream<T5>,
  fn5: (stream: PullStream<T5>) => PullStream<T6>,
  fn6: (stream: PullStream<T6>) => PullStream<T7>,
  fn7: (stream: PullStream<T7>) => PullStream<T8>,
  fn8: (stream: PullStream<T8>) => PullStream<T9>,
  fn9: (stream: PullStream<T9>) => PullStream<T10>,
): PullStream<T10>;
export function pipe<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(
  stream: PullStream<T1>,
  fn1: (stream: PullStream<T1>) => PullStream<T2>,
  fn2: (stream: PullStream<T2>) => PullStream<T3>,
  fn3: (stream: PullStream<T3>) => PullStream<T4>,
  fn4: (stream: PullStream<T4>) => PullStream<T5>,
  fn5: (stream: PullStream<T5>) => PullStream<T6>,
  fn6: (stream: PullStream<T6>) => PullStream<T7>,
  fn7: (stream: PullStream<T7>) => PullStream<T8>,
  fn8: (stream: PullStream<T8>) => PullStream<T9>,
  fn9: (stream: PullStream<T9>) => PullStream<T10>,
  fn10: (stream: PullStream<T10>) => PullStream<T11>,
): PullStream<T11>;
export function pipe<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(
  stream: PullStream<T1>,
  fn1: (stream: PullStream<T1>) => PullStream<T2>,
  fn2: (stream: PullStream<T2>) => PullStream<T3>,
  fn3: (stream: PullStream<T3>) => PullStream<T4>,
  fn4: (stream: PullStream<T4>) => PullStream<T5>,
  fn5: (stream: PullStream<T5>) => PullStream<T6>,
  fn6: (stream: PullStream<T6>) => PullStream<T7>,
  fn7: (stream: PullStream<T7>) => PullStream<T8>,
  fn8: (stream: PullStream<T8>) => PullStream<T9>,
  fn9: (stream: PullStream<T9>) => PullStream<T10>,
  fn10: (stream: PullStream<T10>) => PullStream<T11>,
  fn11: (stream: PullStream<T11>) => PullStream<T12>,
): PullStream<T12>;
export function pipe<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(
  stream: PullStream<T1>,
  fn1: (stream: PullStream<T1>) => PullStream<T2>,
  fn2: (stream: PullStream<T2>) => PullStream<T3>,
  fn3: (stream: PullStream<T3>) => PullStream<T4>,
  fn4: (stream: PullStream<T4>) => PullStream<T5>,
  fn5: (stream: PullStream<T5>) => PullStream<T6>,
  fn6: (stream: PullStream<T6>) => PullStream<T7>,
  fn7: (stream: PullStream<T7>) => PullStream<T8>,
  fn8: (stream: PullStream<T8>) => PullStream<T9>,
  fn9: (stream: PullStream<T9>) => PullStream<T10>,
  fn10: (stream: PullStream<T10>) => PullStream<T11>,
  fn11: (stream: PullStream<T11>) => PullStream<T12>,
  fn12: (stream: PullStream<T12>) => PullStream<T13>,
): PullStream<T13>;
export function pipe<
  T1,
  T2,
  T3,
  T4,
  T5,
  T6,
  T7,
  T8,
  T9,
  T10,
  T11,
  T12,
  T13,
  T14,
>(
  stream: PullStream<T1>,
  fn1: (stream: PullStream<T1>) => PullStream<T2>,
  fn2: (stream: PullStream<T2>) => PullStream<T3>,
  fn3: (stream: PullStream<T3>) => PullStream<T4>,
  fn4: (stream: PullStream<T4>) => PullStream<T5>,
  fn5: (stream: PullStream<T5>) => PullStream<T6>,
  fn6: (stream: PullStream<T6>) => PullStream<T7>,
  fn7: (stream: PullStream<T7>) => PullStream<T8>,
  fn8: (stream: PullStream<T8>) => PullStream<T9>,
  fn9: (stream: PullStream<T9>) => PullStream<T10>,
  fn10: (stream: PullStream<T10>) => PullStream<T11>,
  fn11: (stream: PullStream<T11>) => PullStream<T12>,
  fn12: (stream: PullStream<T12>) => PullStream<T13>,
  fn13: (stream: PullStream<T13>) => PullStream<T14>,
): PullStream<T14>;
export function pipe<
  T1,
  T2,
  T3,
  T4,
  T5,
  T6,
  T7,
  T8,
  T9,
  T10,
  T11,
  T12,
  T13,
  T14,
  T15,
>(
  stream: PullStream<T1>,
  fn1: (stream: PullStream<T1>) => PullStream<T2>,
  fn2: (stream: PullStream<T2>) => PullStream<T3>,
  fn3: (stream: PullStream<T3>) => PullStream<T4>,
  fn4: (stream: PullStream<T4>) => PullStream<T5>,
  fn5: (stream: PullStream<T5>) => PullStream<T6>,
  fn6: (stream: PullStream<T6>) => PullStream<T7>,
  fn7: (stream: PullStream<T7>) => PullStream<T8>,
  fn8: (stream: PullStream<T8>) => PullStream<T9>,
  fn9: (stream: PullStream<T9>) => PullStream<T10>,
  fn10: (stream: PullStream<T10>) => PullStream<T11>,
  fn11: (stream: PullStream<T11>) => PullStream<T12>,
  fn12: (stream: PullStream<T12>) => PullStream<T13>,
  fn13: (stream: PullStream<T13>) => PullStream<T14>,
  fn14: (stream: PullStream<T14>) => PullStream<T15>,
): PullStream<T15>;
export function pipe<
  T1,
  T2,
  T3,
  T4,
  T5,
  T6,
  T7,
  T8,
  T9,
  T10,
  T11,
  T12,
  T13,
  T14,
  T15,
  T16,
>(
  stream: PullStream<T1>,
  fn1: (stream: PullStream<T1>) => PullStream<T2>,
  fn2: (stream: PullStream<T2>) => PullStream<T3>,
  fn3: (stream: PullStream<T3>) => PullStream<T4>,
  fn4: (stream: PullStream<T4>) => PullStream<T5>,
  fn5: (stream: PullStream<T5>) => PullStream<T6>,
  fn6: (stream: PullStream<T6>) => PullStream<T7>,
  fn7: (stream: PullStream<T7>) => PullStream<T8>,
  fn8: (stream: PullStream<T8>) => PullStream<T9>,
  fn9: (stream: PullStream<T9>) => PullStream<T10>,
  fn10: (stream: PullStream<T10>) => PullStream<T11>,
  fn11: (stream: PullStream<T11>) => PullStream<T12>,
  fn12: (stream: PullStream<T12>) => PullStream<T13>,
  fn13: (stream: PullStream<T13>) => PullStream<T14>,
  fn14: (stream: PullStream<T14>) => PullStream<T15>,
  fn15: (stream: PullStream<T15>) => PullStream<T16>,
): PullStream<T16>;
export function pipe<
  T1,
  T2,
  T3,
  T4,
  T5,
  T6,
  T7,
  T8,
  T9,
  T10,
  T11,
  T12,
  T13,
  T14,
  T15,
  T16,
  T17,
>(
  stream: PullStream<T1>,
  fn1: (stream: PullStream<T1>) => PullStream<T2>,
  fn2: (stream: PullStream<T2>) => PullStream<T3>,
  fn3: (stream: PullStream<T3>) => PullStream<T4>,
  fn4: (stream: PullStream<T4>) => PullStream<T5>,
  fn5: (stream: PullStream<T5>) => PullStream<T6>,
  fn6: (stream: PullStream<T6>) => PullStream<T7>,
  fn7: (stream: PullStream<T7>) => PullStream<T8>,
  fn8: (stream: PullStream<T8>) => PullStream<T9>,
  fn9: (stream: PullStream<T9>) => PullStream<T10>,
  fn10: (stream: PullStream<T10>) => PullStream<T11>,
  fn11: (stream: PullStream<T11>) => PullStream<T12>,
  fn12: (stream: PullStream<T12>) => PullStream<T13>,
  fn13: (stream: PullStream<T13>) => PullStream<T14>,
  fn14: (stream: PullStream<T14>) => PullStream<T15>,
  fn15: (stream: PullStream<T15>) => PullStream<T16>,
  fn16: (stream: PullStream<T16>) => PullStream<T17>,
): PullStream<T17>;
export function pipe<
  T1,
  T2,
  T3,
  T4,
  T5,
  T6,
  T7,
  T8,
  T9,
  T10,
  T11,
  T12,
  T13,
  T14,
  T15,
  T16,
  T17,
  T18,
>(
  stream: PullStream<T1>,
  fn1: (stream: PullStream<T1>) => PullStream<T2>,
  fn2: (stream: PullStream<T2>) => PullStream<T3>,
  fn3: (stream: PullStream<T3>) => PullStream<T4>,
  fn4: (stream: PullStream<T4>) => PullStream<T5>,
  fn5: (stream: PullStream<T5>) => PullStream<T6>,
  fn6: (stream: PullStream<T6>) => PullStream<T7>,
  fn7: (stream: PullStream<T7>) => PullStream<T8>,
  fn8: (stream: PullStream<T8>) => PullStream<T9>,
  fn9: (stream: PullStream<T9>) => PullStream<T10>,
  fn10: (stream: PullStream<T10>) => PullStream<T11>,
  fn11: (stream: PullStream<T11>) => PullStream<T12>,
  fn12: (stream: PullStream<T12>) => PullStream<T13>,
  fn13: (stream: PullStream<T13>) => PullStream<T14>,
  fn14: (stream: PullStream<T14>) => PullStream<T15>,
  fn15: (stream: PullStream<T15>) => PullStream<T16>,
  fn16: (stream: PullStream<T16>) => PullStream<T17>,
  fn17: (stream: PullStream<T17>) => PullStream<T18>,
): PullStream<T18>;
export function pipe<
  T1,
  T2,
  T3,
  T4,
  T5,
  T6,
  T7,
  T8,
  T9,
  T10,
  T11,
  T12,
  T13,
  T14,
  T15,
  T16,
  T17,
  T18,
  T19,
>(
  stream: PullStream<T1>,
  fn1: (stream: PullStream<T1>) => PullStream<T2>,
  fn2: (stream: PullStream<T2>) => PullStream<T3>,
  fn3: (stream: PullStream<T3>) => PullStream<T4>,
  fn4: (stream: PullStream<T4>) => PullStream<T5>,
  fn5: (stream: PullStream<T5>) => PullStream<T6>,
  fn6: (stream: PullStream<T6>) => PullStream<T7>,
  fn7: (stream: PullStream<T7>) => PullStream<T8>,
  fn8: (stream: PullStream<T8>) => PullStream<T9>,
  fn9: (stream: PullStream<T9>) => PullStream<T10>,
  fn10: (stream: PullStream<T10>) => PullStream<T11>,
  fn11: (stream: PullStream<T11>) => PullStream<T12>,
  fn12: (stream: PullStream<T12>) => PullStream<T13>,
  fn13: (stream: PullStream<T13>) => PullStream<T14>,
  fn14: (stream: PullStream<T14>) => PullStream<T15>,
  fn15: (stream: PullStream<T15>) => PullStream<T16>,
  fn16: (stream: PullStream<T16>) => PullStream<T17>,
  fn17: (stream: PullStream<T17>) => PullStream<T18>,
  fn18: (stream: PullStream<T18>) => PullStream<T19>,
): PullStream<T19>;
export function pipe<
  T1,
  T2,
  T3,
  T4,
  T5,
  T6,
  T7,
  T8,
  T9,
  T10,
  T11,
  T12,
  T13,
  T14,
  T15,
  T16,
  T17,
  T18,
  T19,
  T20,
>(
  stream: PullStream<T1>,
  fn1: (stream: PullStream<T1>) => PullStream<T2>,
  fn2: (stream: PullStream<T2>) => PullStream<T3>,
  fn3: (stream: PullStream<T3>) => PullStream<T4>,
  fn4: (stream: PullStream<T4>) => PullStream<T5>,
  fn5: (stream: PullStream<T5>) => PullStream<T6>,
  fn6: (stream: PullStream<T6>) => PullStream<T7>,
  fn7: (stream: PullStream<T7>) => PullStream<T8>,
  fn8: (stream: PullStream<T8>) => PullStream<T9>,
  fn9: (stream: PullStream<T9>) => PullStream<T10>,
  fn10: (stream: PullStream<T10>) => PullStream<T11>,
  fn11: (stream: PullStream<T11>) => PullStream<T12>,
  fn12: (stream: PullStream<T12>) => PullStream<T13>,
  fn13: (stream: PullStream<T13>) => PullStream<T14>,
  fn14: (stream: PullStream<T14>) => PullStream<T15>,
  fn15: (stream: PullStream<T15>) => PullStream<T16>,
  fn16: (stream: PullStream<T16>) => PullStream<T17>,
  fn17: (stream: PullStream<T17>) => PullStream<T18>,
  fn18: (stream: PullStream<T18>) => PullStream<T19>,
  fn19: (stream: PullStream<T19>) => PullStream<T20>,
): PullStream<T20>;
export function pipe<
  T1,
  T2,
  T3,
  T4,
  T5,
  T6,
  T7,
  T8,
  T9,
  T10,
  T11,
  T12,
  T13,
  T14,
  T15,
  T16,
  T17,
  T18,
  T19,
  T20,
  T21,
>(
  stream: PullStream<T1>,
  fn1: (stream: PullStream<T1>) => PullStream<T2>,
  fn2: (stream: PullStream<T2>) => PullStream<T3>,
  fn3: (stream: PullStream<T3>) => PullStream<T4>,
  fn4: (stream: PullStream<T4>) => PullStream<T5>,
  fn5: (stream: PullStream<T5>) => PullStream<T6>,
  fn6: (stream: PullStream<T6>) => PullStream<T7>,
  fn7: (stream: PullStream<T7>) => PullStream<T8>,
  fn8: (stream: PullStream<T8>) => PullStream<T9>,
  fn9: (stream: PullStream<T9>) => PullStream<T10>,
  fn10: (stream: PullStream<T10>) => PullStream<T11>,
  fn11: (stream: PullStream<T11>) => PullStream<T12>,
  fn12: (stream: PullStream<T12>) => PullStream<T13>,
  fn13: (stream: PullStream<T13>) => PullStream<T14>,
  fn14: (stream: PullStream<T14>) => PullStream<T15>,
  fn15: (stream: PullStream<T15>) => PullStream<T16>,
  fn16: (stream: PullStream<T16>) => PullStream<T17>,
  fn17: (stream: PullStream<T17>) => PullStream<T18>,
  fn18: (stream: PullStream<T18>) => PullStream<T19>,
  fn19: (stream: PullStream<T19>) => PullStream<T20>,
  fn20: (stream: PullStream<T20>) => PullStream<T21>,
): PullStream<T21>;
export function pipe(
  stream: PullStream<unknown>,
  ...args: ((stream: PullStream<unknown>) => PullStream<unknown>)[]
): PullStream<unknown> {
  return args.reduce((acc, fn) => fn(acc), stream);
}
